### ISSUE TITLE
Enhancement: Add Source/Destination Swap Feature to Firewall Rule Generator

### ISSUE THREAD

**Issue by shikyo13** [shikyo13/zeronexus-website#28]
## Summary
Add a swap/flip functionality to the Firewall Rule Generator that allows users to easily exchange source and destination values. This improvement addresses the common confusion users face when thinking "I need to open RDP on server A from server B" and having to translate that into firewall terminology.

## Problem Statement
Currently, users must understand that firewall rules are configured from the firewall's perspective, not their own. For example:
- User thinks: "I need to allow RDP access **to** Server A **from** Server B"
- Firewall needs: Source = Server B, Destination = Server A

This mental model mismatch causes confusion, especially for beginners who may configure rules backwards and need to re-enter all values.

### Add Swap Button Between Source/Destination Cards
1. **Visual Design**:
   ```
   [Source Card] <--[Swap Button]--> [Destination Card]
   ```
   - Use Font Awesome `fa-exchange-alt` icon (rotated 90 degrees)
   - Position button between the two cards
   - Add hover effect and tooltip: "Swap source and destination"

2. **Functionality**:
   - One-click swap of all values (type, value, port)
   - Maintain validation state
   - Smooth transition animation

3. **Enhanced User Guidance**:
   - Add contextual help text explaining the relationship
   - Include real-world examples
   - Make the direction more intuitive

### 1. HTML Changes (`firewall-rule-generator.php`)
```html
<\!-- Add between source and destination cards -->
<div class="text-center my-3">
    <button type="button" class="btn btn-outline-secondary" id="swapSourceDest" 
            data-bs-toggle="tooltip" title="Swap source and destination">
        <i class="fas fa-exchange-alt fa-rotate-90"></i>
    </button>
</div>

<\!-- Add contextual help -->
<div class="alert alert-info mb-3" id="directionHelp">
    <i class="fas fa-lightbulb me-2"></i>
    <strong>Tip:</strong> Think of rules from the firewall's perspective. 
    To allow RDP <strong>to</strong> ServerA <strong>from</strong> ServerB: 
    Source = ServerB, Destination = ServerA
</div>
```

### 2. JavaScript Changes (`firewall-rule-generator.js`)
```javascript
// Add to setupEventListeners()
document.getElementById('swapSourceDest').addEventListener('click', () => this.swapSourceDestination());

// New method
swapSourceDestination() {
    // Store current values
    const tempSource = {
        type: document.getElementById('sourceType').value,
        value: document.getElementById('sourceValue').value,
        port: document.getElementById('sourcePort').value
    };
    
    const tempDest = {
        type: document.getElementById('destType').value,
        value: document.getElementById('destValue').value,
        port: document.getElementById('destPort').value
    };
    
    // Swap values
    document.getElementById('sourceType').value = tempDest.type;
    document.getElementById('sourceValue').value = tempDest.value;
    document.getElementById('sourcePort').value = tempDest.port;
    
    document.getElementById('destType').value = tempSource.type;
    document.getElementById('destValue').value = tempSource.value;
    document.getElementById('destPort').value = tempSource.port;
    
    // Update UI state
    this.handleTypeChange('source', tempDest.type);
    this.handleTypeChange('dest', tempSource.type);
    
    // Update rule data
    this.updateRuleData();
    
    // Visual feedback
    this.animateSwap();
}

// Animation method
animateSwap() {
    const sourceCard = document.querySelector('#firewallRuleGeneratorModal .card:nth-of-type(1)');
    const destCard = document.querySelector('#firewallRuleGeneratorModal .card:nth-of-type(2)');
    
    sourceCard.style.animation = 'pulse 0.3s ease-in-out';
    destCard.style.animation = 'pulse 0.3s ease-in-out';
    
    setTimeout(() => {
        sourceCard.style.animation = '';
        destCard.style.animation = '';
    }, 300);
}
```

### 3. CSS Changes (`network-admin.css`)
```css
/* Swap button styling */
#swapSourceDest {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.3s ease;
}

#swapSourceDest:hover {
    transform: scale(1.1);
    background-color: rgba(13, 202, 240, 0.2);
    border-color: #0dcaf0;
}

/* Pulse animation for swap feedback */
@keyframes pulse {
    0% { transform: scale(1); }
    50% { transform: scale(0.98); box-shadow: 0 0 10px rgba(13, 202, 240, 0.5); }
    100% { transform: scale(1); }
}

/* Help text styling */
#directionHelp {
    font-size: 0.9rem;
}
```

## Benefits
1. **Improved Usability**: Users can quickly fix backwards configurations
2. **Reduced Errors**: Less chance of misconfigured rules
3. **Better Learning**: Visual swap helps users understand the source/destination relationship
4. **Time Saving**: No need to re-enter values if initially backwards

## Testing Checklist
- [ ] Swap button properly exchanges all values
- [ ] Type-specific field states are maintained (disabled/enabled)
- [ ] Validation works correctly after swap
- [ ] Tooltips display on hover
- [ ] Animation provides smooth visual feedback
- [ ] Help text is clear and useful
- [ ] Mobile responsive layout works
- [ ] No console errors during swap

## Future Enhancements
- Add "Quick Setup Wizard" for common scenarios
- Remember user's preferred mental model (to/from vs source/destination)
- Add visual flow diagram option

---
This implementation plan was created using automated tools and AI analysis. Human review and validation are required before proceeding with implementation.
