### ISSUE TITLE
Implementation Plan: Comprehensive Code Testing and Linting Pipeline

### ISSUE THREAD

**Issue by shikyo13** [shikyo13/zeronexus-website#29]
### Executive Summary
Implement automated code quality checks for PHP, JavaScript, CSS, and HTML across the ZeroNexus website codebase. This will ensure syntactic correctness, enforce best practices, and prevent the use of deprecated methods through GitHub Actions CI/CD pipeline.

---

### Core Need
- Automated syntax validation for all code types (PHP, JS, CSS, HTML)
- Best practice enforcement using latest standards
- Prevention of deprecated method usage
- Integration with existing GitHub Actions workflows

### Key Stakeholders
- **Developers**: Need fast feedback on code quality issues
- **Maintainers**: Require consistent code standards across contributions
- **Users**: Benefit from stable, bug-free website experience

### Assumptions to Validate
- ✅ Project uses GitHub Actions (confirmed: `.github/workflows/` exists)
- ✅ No existing testing framework (confirmed: manual testing only)
- ✅ No dependency management system (confirmed: no package.json/composer.json)
- ❓ Team willing to adopt strict linting rules
- ❓ Acceptable to add dependency management tools

---

### Current State
- **PHP Files**: ~25 files (API endpoints + pages)
- **JavaScript**: ~15 files (vanilla JS, no framework)
- **CSS**: 7 stylesheets (custom + Bootstrap)
- **HTML**: Embedded in PHP files
- **Testing**: Manual only (TESTING_CHECKLIST.md)
- **CI/CD**: Basic deployment workflow with health check

### Affected Components
```
website/
├── api/          # 18 PHP API endpoints
├── js/           # JavaScript modules
├── css/          # Stylesheets
├── *.php         # 5 main page files
.github/
└── workflows/    # GitHub Actions configs
```

### Technical Debt Impact
- No existing linting configs to migrate
- Clean slate for tool selection
- May require minor code fixes for initial compliance

---

#### PHP Tools
- **PHPStan**: Level-based static analysis, excellent Laravel/Symfony support
- **Psalm**: Advanced type checking, XML config, Vimeo-backed
- **PHP_CodeSniffer**: Style enforcement, supports CSS/JS too
- **PHP-CS-Fixer**: Automatic code style fixing

#### JavaScript Tools
- **ESLint**: Industry standard, extensive plugin ecosystem
- **Prettier**: Opinionated code formatter

#### CSS Tools
- **Stylelint**: Modern CSS linter, ESLint-like architecture
- **ESLint CSS**: New 2025 feature for CSS linting via ESLint

#### HTML Tools
- **HTMLHint**: Static code analysis
- **W3C Validator**: Standards compliance
- **Markuplint**: Modern HTML linter

### Security Considerations
- Prevent XSS vulnerabilities through proper escaping validation
- Enforce CSP compliance in inline scripts/styles
- Validate API input sanitization patterns
- Check for SQL injection patterns (even without DB)

### Performance Implications
- CI runtime: ~2-5 minutes for full suite
- Parallel job execution reduces total time
- Caching dependencies speeds subsequent runs
- Fail-fast strategy prevents unnecessary checks

---

### Approach 1: Minimal Integration (Recommended) ⭐
**Description**: Add linting without dependency managers, use Docker for tools

**Pros**:
- Aligns with current architecture (no package managers)
- Self-contained in CI environment
- No local dev environment changes required
- Faster implementation

**Cons**:
- Slightly slower CI runs (no dependency caching)
- Developers can't easily run locally
- Limited tool selection

**Implementation**:
```yaml
- uses: php-actions/phpstan@v3
- uses: php-actions/phpcs@v1
- run: docker run --rm -v $PWD:/data cytopia/eslint .
- run: docker run --rm -v $PWD:/data cytopia/stylelint .
```

### Approach 2: Full Modern Stack
**Description**: Add composer.json and package.json for complete tooling

**Pros**:
- Industry-standard approach
- Local development integration
- Full tool ecosystem access
- Dependency version locking

**Cons**:
- Major architecture change
- Requires local dev setup changes
- More complex deployment

### Approach 3: Hybrid Approach
**Description**: Use GitHub Actions marketplace actions + minimal configs

**Pros**:
- Good balance of features
- No dependency managers needed
- Wide tool selection

**Cons**:
- Relies on third-party actions
- Version management through action tags

---

### Phase 1: Foundation (Complexity: S)
- [ ] Create `.github/workflows/code-quality.yml`
- [ ] Set up workflow triggers (push, PR)
- [ ] Configure job matrix for parallel execution
- [ ] Add workflow status badge to README

### Phase 2: PHP Linting (Complexity: M)
- [ ] Configure PHPStan (level 0 initially)
- [ ] Set up PHP_CodeSniffer with PSR-12
- [ ] Create baseline for existing issues
- [ ] Add custom rules for project patterns

### Phase 3: JavaScript Linting (Complexity: M)
- [ ] Configure ESLint with standard config
- [ ] Add browser environment settings
- [ ] Create .eslintignore for vendor files
- [ ] Handle Bootstrap/third-party code

### Phase 4: CSS Linting (Complexity: S)
- [ ] Set up Stylelint with standard config
- [ ] Configure Bootstrap compatibility
- [ ] Add rules for browser compatibility

### Phase 5: HTML Validation (Complexity: M)
- [ ] Extract HTML from PHP for validation
- [ ] Configure W3C validator
- [ ] Handle dynamic content appropriately
- [ ] Validate embedded Bluesky/external content

### Phase 6: Integration & Reporting (Complexity: L)
- [ ] Aggregate results into single report
- [ ] Configure PR comments for issues
- [ ] Set up problem matchers
- [ ] Create fix suggestions

### Suggested Order:
1. Foundation → PHP → JavaScript → CSS → HTML → Integration

---

### Risks & Mitigation

| Risk | Impact | Mitigation |
|------|--------|------------|
| Too many initial errors | High | Start with lenient rules, progressively stricten |
| Slow CI runs | Medium | Use parallel jobs, fail-fast, caching |
| Developer resistance | Medium | Provide auto-fix tools, clear documentation |
| False positives | Low | Use baseline files, custom rule exceptions |
| Breaking existing code | Low | Non-blocking initially, gradual enforcement |

### Backward Compatibility
- No changes to deployment process
- Existing manual tests remain valid
- Code functionality unchanged
- Optional local development integration

---

### Files to Update
- `CLAUDE.md`: Add linting commands section
- `README.md`: Add quality badge, contributor guidelines
- `docs/DEVELOPMENT.md`: Create with linting setup guide
- `.github/CONTRIBUTING.md`: Add code quality requirements

### Examples to Create
- Sample PHPStan configuration
- ESLint rule customization
- How to run checks locally
- Fixing common violations

### API Changes
- None required (linting is development-only)

---

### GitHub Actions Workflow
```yaml
name: Code Quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: PHPStan Analysis
        uses: php-actions/phpstan@v3
        with:
          path: website/
          level: 0
          
      - name: PHP CodeSniffer
        uses: php-actions/phpcs@v1
        with:
          path: website/
          standard: PSR12

  js-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: ESLint
        run: |
          docker run --rm \
            -v $PWD:/work \
            cytopia/eslint \
            --ext .js \
            website/js/

  css-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Stylelint
        run: |
          docker run --rm \
            -v $PWD:/work \
            cytopia/stylelint \
            'website/css/*.css'
```

### PHPStan Configuration (phpstan.neon)
```neon
parameters:
    level: 0
    paths:
        - website
    excludePaths:
        - website/artwork
    ignoreErrors:
        - '#Call to an undefined method#'
    reportUnmatchedIgnoredErrors: false
```

### ESLint Configuration (.eslintrc.json)
```json
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 12
    },
    "rules": {
        "no-unused-vars": "warn",
        "no-console": "off"
    },
    "globals": {
        "bootstrap": "readonly"
    }
}
```

---

## Success Metrics

- ✅ All code passes syntax validation
- ✅ Zero use of deprecated methods
- ✅ Consistent code style across project
- ✅ CI runs complete in < 5 minutes
- ✅ 90%+ of issues auto-fixable
- ✅ Developer adoption within 2 weeks

---

*This implementation plan was created using automated tools and AI analysis. Human review and validation are required before proceeding with implementation.*
